language: python
python: 2.7

before_install:

 # install code analysis tools
 - pip install pep8 pyflakes

 # install other packages
 - pip install joblib

# install the package
install: python setup.py install

# run tests
script:
 - nosetests
 - pep8 pubchem_utils
 - pyflakes pubchem_utils
