language: python
python: 2.7

# install code analysis tools
before_install:
 - pip install pep8
 - pip install pyflakes
  
# install the package
install: python setup.py install

# run tests
script: 
 - nosetests
 - pep8 pubchem_utils
 - pyflakes pubchem_utils
